In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable


In [1]:
import numpy as np

In [2]:
print(np.__version__)

2.3.5


In [3]:
list1 = [1,2,3]
print(list1)

[1, 2, 3]


In [4]:
array_np_1= np.array(list1)
print(array_np_1)

[1 2 3]


In [5]:
print(array_np_1.ndim)

1


In [6]:
list1 = [1,2,3]
list2 = [4,5,6]
array_np_2=np.array([list1,list2])

In [7]:
print(array_np_2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(array_np_2.ndim)

2


In [9]:
list1 = [1,2,3]
list2 = [4,5,6]
list3 = [7,8,9]
array_np_3=np.array([[list1,list2,list3]])
print(array_np_3)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [20]:
# Attributes in numpy

In [11]:
shape = array_np_3.shape
print("shape matrix : ",shape)

shape matrix :  (1, 3, 3)


In [12]:
zeros = np.zeros((2,3))
print("Print all zeroes number in an array")
print(zeros)

Print all zeroes number in an array
[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
ones = np.ones((2,3))
print("Print all ones number in an array")
print(ones)

Print all ones number in an array
[[1. 1. 1.]
 [1. 1. 1.]]


In [14]:
full = np.full((2,3),4)

print("full Metrix : ")
print(full )

full Metrix : 
[[4 4 4]
 [4 4 4]]


In [31]:
print("Identity mertix")
print(np.eye(3,3))

Identity mertix
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [33]:
print("Empty array : ")
print(np.empty(2))

Empty array : 
[2.e-323 2.e-323]


In [35]:
print("Evenly spaces array : ")
print(np.arange(1,4,1)) #its means it will start from 1 to 4 and add 1 in each value untill it will not beome smallar then 4. Basically i will start from 1 to 4

Evenly spaces array : 
[1 2 3]


In [42]:
#specific number of values equally spaced between a range
print(np.linspace(1,10,5)) # it will split five equal parts because I used 5 at the end to declare the range

[ 1.    3.25  5.5   7.75 10.  ]


In [44]:
#random values generate array in float form
random = np.random.rand(4,3)
print(random)

[[0.66546058 0.87137478 0.89295344]
 [0.01147585 0.24834089 0.9722782 ]
 [0.30783534 0.08415161 0.7840202 ]
 [0.15399358 0.57150894 0.44973122]]


In [48]:
#random values genrate in int form
rand = np.random.randint(1,10,(3,3)) # genrate values from 1 to 10 of 3 by 3  matrix
print(rand)

[[9 4 2]
 [7 4 7]
 [7 5 5]]


In [ ]:
#-------------------------------------------------------------- Arry indexing & slicing------------------------------------------------

In [15]:
a = np.array([1,4,2,5,7,12])
print(a)

[ 1  4  2  5  7 12]


In [16]:
print(a[2]) # for print the index value

2


In [17]:
print(a[-3])

5


In [52]:
#--- Slicing 
# array[start:stop:jump]
#stop index will not include in output 

In [18]:
a = np.array([1,4,2,5,7,12])
a[0:5] # first 5 elements

array([1, 4, 2, 5, 7])

In [19]:
print(a[-5:]) # last 5 elements

[ 4  2  5  7 12]


In [20]:
a[1:5] # middle 4 elements

array([4, 2, 5, 7])

In [22]:
a[0:5:2] # step or jump by 2 elements

array([1, 2, 7])

In [28]:
print(a[0::3])

[1 5]


In [29]:
print(a[-3:])

[ 5  7 12]


In [30]:
#-----------------------------2 Diamonsional array slicing------------------------------------------------------

In [6]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [9]:
print(arr2[0])

[1 2 3]


In [8]:
print(arr2[1])

[4 5 6]


In [19]:
print(arr2[0:,0]) # it will give the one colmn of the first array 
print(arr2[0:,1])
print(arr2[0:,2])
print(arr2[1:,0])
print(arr2[1:,1])
print(arr2[1:,2])

[1 4]
[2 5]
[3 6]
[4]
[5]
[6]


In [20]:
#---------------------------------------stacking and spliting--------------------------

In [22]:
#stacking means to add the arrays in horizantoly and vertically and make dimensional array

In [25]:
a = [1,2,3]
b = [4,5,6]
stack = np.vstack((a,b))
print(stack)

[[1 2 3]
 [4 5 6]]


In [27]:
stack = np.hstack((a,b))
print(stack)

[1 2 3 4 5 6]


In [30]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [34]:
vsplit = np.vsplit(c,2)
print(vsplit)
for s in vsplit:
    print(s)
# splitting means to divide the array in equal parts in columns

[array([[1, 2, 3]]), array([[4, 5, 6]])]
[[1 2 3]]
[[4 5 6]]


In [36]:
hsplit = np.hsplit(c,3)
print(hsplit)
for s in hsplit:
    print(s)
# splitting means to divide the array in equal parts in 3 columns

[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [ ]:
#--------------------------Methametical operations on array

In [38]:
a = np.array([21,4,32])
print(a)

[21  4 32]


In [39]:
print(a+3)
print(a-3)
print(a*3)
print(a/3)

[24  7 35]
[18  1 29]
[63 12 96]
[ 7.          1.33333333 10.66666667]


In [41]:
b = np.array([1,4,9])
print(b)

[1 4 9]


In [42]:
print(np.square(b)) #for square of b
print(np.sqrt(b)) # for square root

[ 1 16 81]
[1. 2. 3.]


In [43]:
a = [1,2,3]
b = [4,5,6]

In [47]:
print(np.dot(a,b)) #its means mutiple the corresponding number of an array and add all of them like(1*4+2*5+3*6=32)
print(np.add(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.subtract(a,b))

32
[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[-3 -3 -3]


In [53]:
a = [1,2,3]
b = [4,5,6]
t = np.array([a,b])
print(t.T) # transpose

[[1 4]
 [2 5]
 [3 6]]


In [54]:
#---------------------satastical functions--------------------

In [57]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
print(np.sum(a))
print(np.mean(a))
print(np.median(a))
print(np.mod(a,b))
print(np.std(a))
print(np.min(a))
print(np.max(a))

In [61]:
#--------------------Array Comparison--------------------------

In [71]:
a = np.array([1,5,3])
b = np.array([4,5,6])
print(a)
print(b)

[1 5 3]
[4 5 6]


In [ ]:
print(a == b) #it compare each element from an arrays
print(a >= b) #it compare each element from an arrays
print(a <= b) #it compare each element from an arrays
print(np.array_equal(a,b)) #comapre the whole array

In [75]:
#-----------------------Broadcasting--------------------------

In [78]:
ar = np.array([[1,2,3],[21,32,12]])
arr = np.array([4])
print(ar)
print(arr)

[[ 1  2  3]
 [21 32 12]]
[4]


In [80]:
print(ar+arr)
print(ar-arr)
print(ar*arr)
print(ar/arr)

[[ 5  6  7]
 [25 36 16]]
[[-3 -2 -1]
 [17 28  8]]
[[  4   8  12]
 [ 84 128  48]]
[[0.25 0.5  0.75]
 [5.25 8.   3.  ]]


In [81]:
#-----------------------------------------------------handling with null values and inf-----------------------------

In [83]:
data = np.array([1,3,np.nan,5,np.inf])
print(data)

[ 1.  3. nan  5. inf]


In [84]:
print(np.isnan(data))

[False False  True False False]


In [85]:
print(np.nan_to_num(data))

[1.00000000e+000 3.00000000e+000 0.00000000e+000 5.00000000e+000
 1.79769313e+308]


In [86]:
#---------------------------save and load------------------

In [87]:
np.save("my_array.npy",data)

In [88]:
load = np.load("my_array.npy")
print(load)

[ 1.  3. nan  5. inf]


In [89]:
#Home work

In [99]:
matrix = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(matrix)
#other solution
print('The next method matrix')
m = np.random.randint(1,25,(5,5))
print(m)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
The next method matrix
[[15 23  6 18 11]
 [24 17  4 20 18]
 [ 1 24 24  2 18]
 [20 22 18 15 17]
 [18  2  2 12 22]]


In [93]:
print(matrix[4])

[21 22 23 24 25]


In [105]:
print(matrix[0:,0])
#other method
print(m[4])
print(m[:,0])

[ 1  6 11 16 21]
[18  2  2 12 22]
[15 24  1 20 18]


In [107]:
#sub martix containg
print(matrix[0:3,0:3])

[[ 1  2  3]
 [ 6  7  8]
 [11 12 13]]


In [108]:
# Broad casting

In [109]:
arr1 = np.random.randint(1,10,(3,1))
print(arr1)

[[9]
 [9]
 [3]]


In [111]:
arr2 = np.random.randint(1,29,(3))
print(arr2)

[16  9 20]


In [112]:
print(arr1*arr2)

[[144  81 180]
 [144  81 180]
 [ 48  27  60]]
